{{- if and .Values.ingressutil.ingress.enabled (gt (len .Values.ingressutil.ingress.items) 0) -}}
{{- range $i, $item := .Values.ingressutil.ingress.items }}
{{ include "ingressutil.ingress" (dict "ing" $item) }}
{{"---"}}
{{- end -}}
{{- else -}}
{{- /* No ingress resources rendered: ingress.items is empty or ingress.enabled is false. */ -}}
{{- end -}}