{{- range $db := .Values.databases }}
{{- $name := $db.name | required "databases[].name is required" }}
{{- $rwSecretName := printf "%s-rw-secret" $name }}
{{- $roSecretName := printf "%s-ro-secret" $name }}
{{- $rwExisting := lookup "v1" "Secret" $.Release.Namespace $rwSecretName }}
{{- $roExisting := lookup "v1" "Secret" $.Release.Namespace $roSecretName }}
{{- $rwPassword := "" }}
{{- if $rwExisting }}
  {{- $rwPassword = $rwExisting.data.password | b64dec }}
{{- else }}
  {{- $rwPassword = randAlphaNum 24 }}
{{- end }}
{{- $roPassword := "" }}
{{- if $roExisting }}
  {{- $roPassword = $roExisting.data.password | b64dec }}
{{- else }}
  {{- $roPassword = randAlphaNum 24 }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rwSecretName }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    "k8s.mariadb.com/watch": ""
type: Opaque
stringData:
  password: {{ $rwPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $roSecretName }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    "k8s.mariadb.com/watch": ""
type: Opaque
stringData:
  password: {{ $roPassword | quote }}
{{- end }}
