# Secret for read-write user
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-app-rw
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  password: {{ randAlphaNum 16 | quote }}
---
# Secret for read-only user
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-app-ro
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  password: {{ randAlphaNum 16 | quote }}

