{{- range $db := .Values.databases }}
{{- $name := $db.name | required "databases[].name is required" }}
{{- $database := $db.database | default $name }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ $name }}-rw
  namespace: {{ $.Release.Namespace }}
spec:
  mariaDbRef:
    name: {{ $name }}
  passwordSecretKeyRef:
    name: {{ $name }}-rw-secret
    key: password
  host: "%"
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ $name }}-rw-grant
  namespace: {{ $.Release.Namespace }}
spec:
  mariaDbRef:
    name: {{ $name }}
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
    - "CREATE"
    - "DROP"
    - "INDEX"
    - "ALTER"
  database: {{ $database }}
  table: "*"
  username: {{ $name }}-rw
{{- end }}
