{{- range $db := .Values.databases }}
{{- $name := $db.name | required "databases[].name is required" }}
{{- $database := $db.database | default $name }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ $name }}-ro
  namespace: {{ $.Release.Namespace }}
spec:
  mariaDbRef:
    name: {{ $name }}
  passwordSecretKeyRef:
    name: {{ $name }}-ro-secret
    key: password
  host: "%"
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: {{ $name }}-ro-grant
  namespace: {{ $.Release.Namespace }}
spec:
  mariaDbRef:
    name: {{ $name }}
  privileges:
    - "SELECT"
  database: {{ $database }}
  table: "*"
  username: {{ $name }}-ro
{{- end }}
