{{- /* per-database secret; generate passwords if not set */ -}}
{{- $db := .Values.database -}}
apiVersion: v1
kind: Secret
metadata:
  name: $db.secretName
  labels:
    app: {{ $db.name | default "mariadb" }}
stringData:
  username: {{ ($db.username) | quote }}
  password: {{ randAlphaNum 32 | quote }}
  root-password: {{ randAlphaNum 32 | quote }}



